### ISSUE TITLE
Migrate to 𝓣𝓱𝓮 𝓒𝓵𝓸𝓾𝓭

### ISSUE THREAD

**Issue by JustinLex** [TMEIT/website#46]
We've decided that hosting should be on a cloud host, so we should migrate hosting to use AWS and its services. Services like Elastic Beanstalk, databases, and S3.

**Comment by loffa** [comment]
I think that we still need Kistan/Our own servers for testing purposes
until the new website has reached the 1.0 version.

It would not be logical to start paying until we have something that is up
and running. Until the our "dev" deployments should be to our own servers
to avoid paying for the AWS/infrastructure.

**Comment by JustinLex** [comment]
Did some shopping around, and it looks like Linode/Digital Ocean would be the best option. $10/month will get us a nano instance with 1GB of RAM and a 15GB ephemeral SSD, and 250 GB of S3 storage that we can use to host all the static files and back up the database to. We could also have a free Cloudflare cache in front of this for handling our DNS and doing easy caches.

We should be able to run the whole thing with infrastructure as code, which will hopefully prevent the need for any hosting maintainance. With Linode, we can use a Stackscript that runs on instance creation to clone the git repo, install dependencies and start the WSGI server. Our CI will use the Linode API to handle the automation. I'm also thinking about migrating from Travis CI to Github Actions (free), just so we have one less website involved.

We need to make sure that this is all set up with TMEIT accounts, though. I'm thinking that we should make a Webb email account for setting this up, and make sure all Webb, TM, and vTM have access to the Linode and Cloudflare accounts.

**Comment by JustinLex** [comment]
We're using Hetzner+Backblaze. 1-2 vcpus, 2-8GB of ram, 20GB of ssd, and 10GB of S3 for 12 euros a month. All CI/CD handled with Github Actions, Terraform, and Kubernetes. All of the accounts are "TMEIT" accounts, but effectively owned by me.
