### ISSUE TITLE
Database storage of user accounts

### ISSUE THREAD

**Issue by loffa** [TMEIT/website#5]
How do we store the user information for registered users.
Fields required is:

- Full Name
- Email
- Phone number
- Drivers licence
- STAD
- Fest
- On permit

A number of photos to each user.

Additionally users are organized in categories (masters, marskalk, prao, vraq, ex) and also in teams while working. We also need to preserve the dates for when a user got the categories. Eg. Became prao at 2018-11-13 and marskalk at 2020-11-13. 

Teams is not fixed in size. It should be possible to change name and members of each team.

**Comment by JustinLex** [comment]
This works! :D
